# Root folder
root = "."
tmp_dir = "tmp"

[build]
cmd = "/usr/bin/go build -o ./tmp/server.exe ./cmd/server"
entrypoint = "tmp/server.exe"
include_ext = ["go"]
exclude_dir = ["tmp", "vendor"]

[log]
time = true
